name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Installs cmdline-tools + sdkmanager, platform API 35, build-tools 35.0.0,
      # and exports ANDROID_HOME/PATH for the rest of the job.
      - name: Setup Android SDK (API 35)
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          components: "build-tools;35.0.0"

      # Some runners still require an explicit license accept step.
      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"  # match your local Flutter

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test

      - name: Build debug APK
        run: flutter build apk --debug --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: BillTipper-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk