name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Android SDK + build-tools 35 installed and on PATH
      - name: Setup Android SDK (API 35)
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          components: "build-tools;35.0.0"

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Flutter doctor (debug info)
        run: flutter doctor -v

      - name: Flutter pub get
        run: flutter pub get

      # Analyzer errors shouldn't fail CI right now
      - name: Analyze (non-blocking)
        run: flutter analyze || echo "Analyzer warnings ignored for CI"

      - name: Test (non-blocking)
        run: flutter test || echo "Tests skipped/failed; continuing for build"

      - name: Build debug APK
        run: flutter build apk --debug --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: BillTipper-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk