name: Flutter CI (Debug APK)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: "stable"
          architecture: x64

      - name: Flutter doctor (diagnostics)
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      # 🔧 REGENERATE ANDROID PLATFORM FOLDER IF MISSING/CORRUPTED
      # This will (re)create android/ without overwriting your lib/, assets/, or pubspec.yaml
      - name: Ensure Android project exists
        run: flutter create --platforms=android .

      # Optional: show Gradle and Android config
      - name: Print Android project files
        run: ls -la android && cat android/gradle.properties || true

      # Build a debug APK (no shrink avoids R8 rules while we iterate)
      - name: Build debug APK (no shrink)
        run: flutter build apk --debug --no-shrink

      # Upload artifact so you can download the APK from the run page
      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk