name: Flutter CI (Debug APK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter 3.24.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'   # <— pin exact version to avoid resolver issues
          cache: true

      - name: Flutter doctor (diagnostics)
        run: flutter doctor -v

      - name: Ensure Android project exists
        run: |
          if [ ! -d "android" ]; then
            echo "No android/ directory — creating Flutter project files…"
            flutter create --platforms=android .
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Force compileSdk = 35
        run: |
          set -e
          GRADLE_FILE="android/app/build.gradle"
          if grep -q "compileSdk" "$GRADLE_FILE"; then
            sed -i 's/compileSdk *=[^0-9]*/compileSdk = 35/' "$GRADLE_FILE" || true
            sed -i 's/compileSdkVersion *[0-9][0-9]*/compileSdkVersion 35/' "$GRADLE_FILE" || true
          fi
          echo "android.enableR8=false" >> android/gradle.properties

      - name: Build debug APK (no shrink)
        run: flutter build apk --debug --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: |
            build/app/outputs/**/*.apk
            **/outputs/**/*.apk
          if-no-files-found: error

      - name: Upload build logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            **/*.log
            build/**/*